---
title: "Garbage Collector Impact"
author: "David Ferreira Quaresma (david.quaresma@ccc.ufcg.edu.br)"
date: "dezembro, 2018"
output: html_document
---

```{r setup, include=FALSE}
require(dplyr)
require(stringr)
require(cowplot)
require(ggplot2)
require(reshape2)
```

```{r}
results = read.csv("../curl-workload/results/r0.csv", header=T, dec=".")
plot(results$business_time.ms., results$scavenge_count + results$marksweep_count, xlim=c(0,750), xlab="tempo de execução (ms)", ylab="numero de coletas")
```

```{r}
nocollect <- filter(results, scavenge_count + marksweep_count == 0)
boxplot(nocollect$business_time.ms., outline=FALSE)
```

```{r}
mean(nocollect$business_time.ms.)
var(nocollect$business_time.ms.)
sd(nocollect$business_time.ms.)
quantile(nocollect$business_time.ms.)
```



```{r}
withcollect <- filter(results, scavenge_count + marksweep_count > 0)
boxplot(withcollect$business_time.ms., outline=FALSE)
```

```{r}
mean(withcollect$business_time.ms.)
var(withcollect$business_time.ms.)
sd(withcollect$business_time.ms.)
quantile(withcollect$business_time.ms.)
```